In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)

In [6]:
A

array([-0.12609417,  0.07101456,  2.68477535,  1.2072206 ,  0.51750801,
        1.04820335,  0.33510686, -0.49437645,  1.35454803, -1.72523587])

In [7]:
B = np.random.randn(10)
B

array([-0.04761362, -0.28109104,  0.11504088, -1.80451568, -0.19324639,
        0.52396231,  0.49709205, -0.50598084,  0.94229012, -0.3070507 ])

In [9]:
#Binary Functions
np.add(A,B)

array([-0.17370779, -0.21007647,  2.79981623, -0.59729508,  0.32426163,
        1.57216566,  0.83219891, -1.00035729,  2.29683815, -2.03228657])

In [10]:
np.maximum(A,B)

array([-0.04761362,  0.07101456,  2.68477535,  1.2072206 ,  0.51750801,
        1.04820335,  0.49709205, -0.49437645,  1.35454803, -0.3070507 ])

In [12]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser 
webbrowser.open(website)

True