In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [5]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [10]:
ser1

T    0
U    1
V    2
dtype: int64

In [11]:
ser2

X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [15]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [19]:
pd.concat([ser1,ser2],axis=0)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [20]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [21]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [22]:
dframe1

X         Y         Z
0  1.112829 -1.064051  0.596446
1  2.092224 -0.326894 -0.791410
2 -0.057125  1.161701  0.777452
3 -0.262651  0.374002 -0.389173

In [23]:
dframe2

Y         Q         X
0 -1.064357 -0.790189 -1.537398
1 -0.456703 -0.418864 -2.250091
2 -0.100769  1.551193 -0.048941

In [25]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  1.112829 -1.064051  0.596446
1       NaN  2.092224 -0.326894 -0.791410
2       NaN -0.057125  1.161701  0.777452
3       NaN -0.262651  0.374002 -0.389173
0 -0.790189 -1.537398 -1.064357       NaN
1 -0.418864 -2.250091 -0.456703       NaN
2  1.551193 -0.048941 -0.100769       NaN

In [26]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  1.112829 -1.064051  0.596446
1       NaN  2.092224 -0.326894 -0.791410
2       NaN -0.057125  1.161701  0.777452
3       NaN -0.262651  0.374002 -0.389173
4 -0.790189 -1.537398 -1.064357       NaN
5 -0.418864 -2.250091 -0.456703       NaN
6  1.551193 -0.048941 -0.100769       NaN

In [28]:
url = 'https://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'